### ISSUE TITLE
trigger (travis) tests from another repo

### ISSUE THREAD

**Issue by boly38** [geokrety/geokrety-website-qa#12]
Following #9 
>We can configure repo geokrety-website to trigger launch via a GitHub webhook to this travis (we should take care to wait for the new docker image to be built and deployed, maybe checking the commit id at the bottom of the page in a loop?) - BTW: we could imagine the same for the master branch and rec instance -

----
from test repo
- [x] provide X reports as results : cf. #13
   - [x] add branch_name as parameter
- [x] provide a new report in addition to a previous one : cf #15
- SKIPPED ~~try webhook~~
----
from geokrety-website repo
- [x] update travis to call webhook under deploy condition : cf https://github.com/geokrety/geokrety-website/issues/193

----
- [ ] travis build tested and fully fonctionnal

**Comment by boly38** [comment]
travis API to request build:

https://docs.travis-ci.com/user/triggering-builds/

we could also send notification to irc instead of by mail:
https://docs.travis-ci.com/user/notifications/#configuring-irc-notifications

**Comment by kumy** [comment]
@boly38 do you have the necessary permission to setup the webhooks?

**Comment by kumy** [comment]
I'm very fan of your current ongoing work! 🏆

**Comment by boly38** [comment]
@kumy you were absolutely right !

I haven't "geokrety" organization for my boly38 "travis developper"'s account 
  https://travis-ci.com/account/preferences

I got only "geokrety" organization for "build related" account :
  https://travis-ci.org/account/preferences )


I will need you to 
- either add me to geokrety on developer side or get travis (geokrety developper) token from https://travis-ci.com/account/preferences 
- then **set an secret variable `TRAVIS_QA_TOCKEN` with this token value** in geokrety-website section :
https://travis-ci.org/geokrety/geokrety-website/settings

please, in order to match with `feature/webhookQA` branch , keep the following name: `TRAVIS_QA_TOCKEN`


If I'm using my own token, I got this result:

    {
      "@type": "error",
      "error_type": "wrong_credentials",
      "error_message": "access denied"
    }

**Comment by kumy** [comment]
I have set your GH account as "owner" is it sufficient? I cannot find memeber settings in travis-ci.org :/

**Comment by boly38** [comment]
Yep but you were right, I was testing `.com`instead of `.org`. What a fool  ;)

**Comment by boly38** [comment]
fixed with https://github.com/geokrety/geokrety-website/issues/193
